actions:
  - name: commit
    desc: commit changes to current branch
    content:
      - command: git add -A
      - command: git commit -m "${m}"
    default:
      - m: no-commit-message

  - name: push
    desc: commit & push changes to current branch
    content:
      - command: git add -A
      - command: git commit -m "${m}"
      - command: git push ${r} ${b}
    default:
      - m: no-commit-message
      - r: origin
      - b: master

  - name: compile
    desc: compiling latest version for all plateforms
    content:
      - command: rm -rf dist/
      - command: goxc -d=${dist} -pv=${pv}
    default:
      - dist: dist
