actions:
  - name: add
    desc: commit changes to current branch
    content:
      - command: git add -A

  - name: commit
    desc: commit changes to current branch
    content:
      - command: git commit -m "${m}"
    default:
      - m: no-commit-message

  - name: push
    desc: commit & push changes to current branch
    content:
      - action: add
      - action: commit
      - command: git push ${r} ${b}
    default:
      - r: origin
      - m: no-commit-message
      - b: $(git symbolic-ref --short -q HEAD)

  - name: compile
    desc: compiling latest version for all plateforms
    content:
      - command: rm -rf dist/
      - command: goxc -d=${dist} -pv=${pv}
    default:
      - dist: dist
